# Agent info
template_root = "hapigov.index.html"
name = "Sở kế hạch và đầu tư thành Phố Hà Nội"
abbreviation = "Hapi"
jurisdiction_name = "Vietnam"
jurisdiction_abbreviation = "VN"

# Webpage info
title = "Sở kế hạch và đầu tư thành Phố Hà Nội"
description = " "
explanation = " "

more_styles = [
  "css/hapi.css"
]

# Forms:
# 
# These structures are used to build the forms
# in the UI.

[[forms]]
name = "identity"
title = "Chứng nhận thành lập công ty"

  [[forms.hidden]]
  name = "schema"
  value = "entry.company"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "person_first_name"
  pretty = "Person First Name"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "person_last_name"
  pretty = "Person Last Name"

  

  [[forms.inputs]]
  type = "text"
  required = true
  name = "duns"
  pretty = "DUNS Number"


  [[forms.inputs]]
  type = "text"
  required = true
  name = "company_name"
  pretty = "Company name"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "company_address"
  pretty = "Address"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "phone"
  pretty = "Phone"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "email"
  pretty = "Email"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "website"
  pretty = "Webiste"


# Schema mappers:
# 
# One for each schema type.
# 
# Each mapper is invoked when a request is received
# which contains value "schema" which maps to "for"
# property.

# ***** TODO *****

[[schema_mappers]]
for = "entry.company"


  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="helper"
  source = "now"

  [[schema_mappers.attributes]]
  name = "person_first_name"
  from ="request"
  source = "person_first_name"

  [[schema_mappers.attributes]]
  name = "person_last_name"
  from ="request"
  source = "person_last_name"

  [[schema_mappers.attributes]]
  name = "company_name"
  from ="request"
  source = "company_name"

  [[schema_mappers.attributes]]
  name = "company_address"
  from ="request"
  source = "company_address"


  [[schema_mappers.attributes]]
  name = "phone"
  from ="request"
  source = "phone"

  [[schema_mappers.attributes]]
  name = "email"
  from ="request"
  source = "email"

  [[schema_mappers.attributes]]
  name = "website"
  from ="request"
  source = "website"

  [[schema_mappers.attributes]]
  name = "duns"
  from ="request"
  source = "duns"

  [[schema_mappers.attributes]]
  name = "end_date"
  from ="literal"
