# Agent info
template_root = "icheck_corp.index.html"
name = "Icheck Corporation"
abbreviation = "icheck"
jurisdiction_name = "Viet Nam"
jurisdiction_abbreviation = "VN"

# Webpage info
title = "Icheck Corporation"
description = "A company that hires anyone skilled enough to graduate from Hanoi University of Science and Technology"
explanation = "Use the form below to apply for a job."

more_styles = [
  "css/icheck_corp.css"
]

# Forms:
# 
# These structures are used to build the forms
# in the UI.

[[forms]]
name = "job_certificate"
title = "Job Certificate"

  [[forms.hidden]]
  name = "schema"
  value = "job_certificate.icheck_corp"


  [[forms.inputs]]
  type = "text"
  required = true
  name = "first_name"
  pretty = "First Name"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "last_name"
  pretty = "Last Name"

  [[forms.inputs]]
  type = "select"
  options = [
    "",
    "Full-time",
    "Part-time",
    "Intern",
    "Retired"
  ]
  required = true
  name = "employee_status"
  pretty = "Employee Status"

  [[forms.inputs]]
  type = "select"
  options = [
    "",
    "<1 yr",
    "1-5 yrs",
    "5-10 yrs",
    "10-15 yrs",
    "15-20 yrs",
    "20+ yrs"
  ]
  required = true
  name = "experience"
  pretty = "Experience"

  [[forms.inputs]]
  type = "select"
  options = [
    "",
    "<$25K",
    "$25K-$50K",
    "$50K-$75K",
    "$75K-$100K",
    "$100-$150K",
    "$150-$200K",
    "$200K+"
  ]
  required = true
  name = "salary_bracket"
  pretty = "Salary Bracket"


[[schema_mappers]]
for = "job_certificate.icheck_corp"

  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="helper"
  source = "now"


  [[schema_mappers.attributes]]
  name = "first_name"
  from ="request"
  source = "first_name"

  [[schema_mappers.attributes]]
  name = "last_name"
  from ="request"
  source = "last_name"

  [[schema_mappers.attributes]]
  name = "employee_status"
  from ="request"
  source = "employee_status"

  [[schema_mappers.attributes]]
  name = "experience"
  from ="request"
  source = "experience"

  [[schema_mappers.attributes]]
  name = "salary_bracket"
  from ="request"
  source = "salary_bracket"





